# Generated by Django 6.0.3 on 2026-03-31 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0001_initial'),
        ('tours', '0002_tourimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='hotels',
            field=models.ManyToManyField(blank=True, related_name='tours', to='hotels.hotel'),
        ),
    ]
