# Generated by Django 6.0.3 on 2026-03-31 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0003_tour_hotels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourimage',
            name='image',
            field=models.ImageField(upload_to='tour_images/'),
        ),
    ]
