# Generated by Django 6.0.3 on 2026-05-17 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0004_alter_tourimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='manager_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='manager_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='manager_phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
