# Generated by Django 6.0.3 on 2026-05-17 08:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0002_hotel_image'),
        ('reviews', '0001_initial'),
        ('tours', '0004_alter_tourimage_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(fields=('user', 'tour'), name='unique_user_tour_review'),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(fields=('user', 'hotel'), name='unique_user_hotel_review'),
        ),
    ]
