# Generated by Django 6.0.3 on 2026-05-17 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_booking_refund_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='people_count',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
